-- Create user_signature table for storing user signatures
-- This table stores signatures generated by users (either sent to system or generated on runtime from PIN)
CREATE TABLE user_signature (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    authentication_credential_id UUID NOT NULL REFERENCES authentication_credentials(id) ON DELETE CASCADE,

    -- The message that was signed
    sign_message TEXT NOT NULL,

    -- The signature hash
    signature TEXT NOT NULL,

    -- Optional: Blockchain deadline block number
    deadline_block INTEGER,

    -- Optional: Estimated deadline datetime (for display purposes)
    estimated_deadline TIMESTAMPTZ,

    -- Track whether the action was broadcasted to blockchain
    -- NULL = not broadcasted, timestamp = when it was broadcasted
    broadcasted_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments on table and columns
COMMENT ON TABLE user_signature IS 'Stores user signatures sent to system or generated on runtime from user PIN';
COMMENT ON COLUMN user_signature.authentication_credential_id IS 'Reference to the user that created this signature';
COMMENT ON COLUMN user_signature.sign_message IS 'The message that was signed';
COMMENT ON COLUMN user_signature.signature IS 'The signature hash';
COMMENT ON COLUMN user_signature.deadline_block IS 'Blockchain deadline block number (optional)';
COMMENT ON COLUMN user_signature.estimated_deadline IS 'Estimated deadline datetime for display purposes (optional)';
COMMENT ON COLUMN user_signature.broadcasted_at IS 'Timestamp when the action was broadcasted to blockchain (NULL if not broadcasted)';

-- Create indexes for efficient querying
CREATE INDEX idx_user_signature_authentication_credential_id ON user_signature(authentication_credential_id);
CREATE INDEX idx_user_signature_created_at ON user_signature(created_at);
CREATE INDEX idx_user_signature_deadline_block ON user_signature(deadline_block) WHERE deadline_block IS NOT NULL;
CREATE INDEX idx_user_signature_estimated_deadline ON user_signature(estimated_deadline) WHERE estimated_deadline IS NOT NULL;
CREATE INDEX idx_user_signature_broadcasted_at ON user_signature(broadcasted_at) WHERE broadcasted_at IS NOT NULL;

-- Create trigger for automatic updated_at timestamp updates
CREATE TRIGGER update_user_signature_updated_at
    BEFORE UPDATE ON user_signature
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Add foreign key from event_attendees to user_signature
-- This links event attendance records to the signature used when joining
ALTER TABLE event_attendees
ADD COLUMN user_signature_id UUID REFERENCES user_signature(id) ON DELETE SET NULL;

-- Add index on the foreign key for efficient lookups
CREATE INDEX idx_event_attendees_user_signature_id ON event_attendees(user_signature_id);

-- Add comment explaining the relationship
COMMENT ON COLUMN event_attendees.user_signature_id IS 'Reference to the signature used when joining this event (optional)';

-- Add foreign key from event_certificates to user_signature
-- This links certificate records to the signature used when claiming
ALTER TABLE event_certificates
ADD COLUMN user_claim_signature_id UUID REFERENCES user_signature(id) ON DELETE SET NULL;

-- Add index on the foreign key for efficient lookups
CREATE INDEX idx_event_certificates_user_claim_signature_id ON event_certificates(user_claim_signature_id);

-- Add comment explaining the relationship
COMMENT ON COLUMN event_certificates.user_claim_signature_id IS 'Reference to the signature used when claiming this certificate (optional)';
