// Package contracts provides a unified import for all smart contract bindings.
// This file is auto-generated by scripts/generate-go-bindings.js
// Do not edit this file directly

package contracts

import (
    "apps/backend/contracts/event"
    "apps/backend/contracts/accessmanager"
    "apps/backend/contracts/ticket"
    "apps/backend/contracts/certificate"
    "apps/backend/contracts/decm"
)

// ContractBindings holds all contract bindings
type ContractBindings struct {
    Event              *event.Event
    EventAccessManager *accessmanager.EventAccessManager
    EventTicket        *ticket.EventTicket
    EventCertificate   *certificate.EventCertificate
    DecmAccessManager  *decm.DecmAccessManager
}
