reviews:
    path_filters:
        - "!packages/api/src/apis/**/api.ts"
        - "!**/node_modules/**"
        - "!**/dist/**"
        - "!**/build/**"
        - "!**/pkg/**"
        - "!**/*.svg"
        - "!**/*.json"
        - "!pnpm-lock.yaml"
        - "!**/gen/**"
