reviews:
    path_filters:
        # Include application files
        - "apps/backend/**"
        - "apps/web/**"
        - "packages/**"
        - "apps/contracts"
        # Exclude generated and build artifacts
        - "!packages/api/src/apis/**/api.ts"
        - "!**/node_modules/**"
        - "!**/dist/**"
        - "!**/build/**"
        - "!**/pkg/**"
        - "!**/generated/**"
        - "!**/contracts/lib"
        - "!**/contracts/out"
        - "!**/contracts/cache"
        - "!**/contracts/.github"
        # Exclude other non-code files
        - "!**/*.svg"
        - "!**/*.json"
        - "!pnpm-lock.yaml"
        - "!**/gen/**"
