// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/onboard/register-with-wallet": {
            "post": {
                "description": "Register a new user with wallet address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Register a new user with wallet address",
                "operationId": "register-with-wallet",
                "parameters": [
                    {
                        "description": "Signed message",
                        "name": "signed_message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Wallet address",
                        "name": "wallet_address",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/customerror.ErrResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/onboard/sign-message": {
            "get": {
                "description": "Retrieve preset message for the client to sign to register",
                "produces": [
                    "application/json"
                ],
                "summary": "Get preset message for the client to sign to register",
                "operationId": "get-register-sign-message",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/onboard.getRegisterSignMessageResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "customerror.ErrResponse": {
            "description": "Response for the client to sign to register",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "onboard.getRegisterSignMessageResponse": {
            "description": "Response for the client to sign to register",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "DECM Core",
	Description:      "DECM (Decentralized Event Management) platform API for NFT ticketing, digital credentials, and academic identity verification.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
