basePath: /
definitions:
  customerror.Err:
    description: Custom error type
    properties:
      code:
        type: string
      http_status:
        type: integer
      message:
        type: string
      reasons:
        additionalProperties:
          type: string
        type: object
    type: object
  customerror.ErrResponse:
    description: Response for the client to sign to register
    properties:
      message:
        type: string
    type: object
  entity.Profile:
    properties:
      academic_email:
        type: string
      academic_institution:
        type: string
      address:
        type: string
      authentication_credential_id:
        type: string
      bio:
        type: string
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_academic_email_public:
        type: boolean
      is_academic_institution_public:
        type: boolean
      is_address_public:
        type: boolean
      is_bio_public:
        type: boolean
      is_email_public:
        type: boolean
      is_first_name_public:
        type: boolean
      is_last_name_public:
        type: boolean
      is_phone_number_public:
        type: boolean
      is_profile_picture_public:
        type: boolean
      last_name:
        type: string
      phone_number:
        type: string
      profile_picture_url:
        type: string
      updated_at:
        type: string
    type: object
  onboard.CheckOnboardStatusRequest:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      method:
        allOf:
        - $ref: '#/definitions/onboard.RegistrationMethod'
        enum:
        - google
        - wallet
      sign_message:
        type: string
    required:
    - method
    type: object
  onboard.CheckOnboardStatusResponse:
    properties:
      authentication_credential_id:
        type: string
      profile_id:
        type: string
    type: object
  onboard.RegistrationMethod:
    enum:
    - google
    - wallet
    type: string
    x-enum-varnames:
    - RegistrationMethodGoogle
    - RegistrationMethodWallet
  onboard.getRegisterSignMessageResponse:
    description: Response for the client to sign to register
    properties:
      message:
        type: string
    type: object
  onboard.registerWithGoogleOAuthRequest:
    properties:
      access_token:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - password
    type: object
  onboard.registerWithGoogleOAuthResponse:
    properties:
      mnemonic:
        items:
          type: string
        type: array
    type: object
  onboard.registerWithWalletRequest:
    properties:
      signed_message:
        type: string
    type: object
  profile.CreateProfileRequest:
    properties:
      academic_email:
        type: string
      academic_institution:
        maxLength: 255
        minLength: 3
        type: string
      address:
        maxLength: 255
        minLength: 10
        type: string
      authentication_credential_id:
        type: string
      bio:
        maxLength: 255
        minLength: 10
        type: string
      email:
        maxLength: 64
        type: string
      first_name:
        maxLength: 32
        minLength: 3
        type: string
      is_academic_email_public:
        type: boolean
      is_academic_institution_public:
        type: boolean
      is_address_public:
        type: boolean
      is_bio_public:
        type: boolean
      is_email_public:
        type: boolean
      is_first_name_public:
        type: boolean
      is_last_name_public:
        type: boolean
      is_phone_number_public:
        type: boolean
      is_profile_picture_public:
        type: boolean
      last_name:
        maxLength: 32
        minLength: 3
        type: string
      phone_number:
        type: string
      profile_picture_url:
        type: string
    required:
    - authentication_credential_id
    type: object
  profile.CreateProfileResponse:
    properties:
      academic_email:
        type: string
      academic_institution:
        type: string
      address:
        type: string
      authentication_credential_id:
        type: string
      bio:
        type: string
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_academic_email_public:
        type: boolean
      is_academic_institution_public:
        type: boolean
      is_address_public:
        type: boolean
      is_bio_public:
        type: boolean
      is_email_public:
        type: boolean
      is_first_name_public:
        type: boolean
      is_last_name_public:
        type: boolean
      is_phone_number_public:
        type: boolean
      is_profile_picture_public:
        type: boolean
      last_name:
        type: string
      phone_number:
        type: string
      profile_picture_url:
        type: string
      updated_at:
        type: string
    type: object
  profile.UpdateProfileRequest:
    properties:
      academic_email:
        type: string
      academic_institution:
        maxLength: 255
        minLength: 3
        type: string
      address:
        maxLength: 255
        minLength: 10
        type: string
      bio:
        maxLength: 255
        minLength: 10
        type: string
      email:
        maxLength: 64
        type: string
      first_name:
        maxLength: 32
        minLength: 3
        type: string
      is_academic_email_public:
        type: boolean
      is_academic_institution_public:
        type: boolean
      is_address_public:
        type: boolean
      is_bio_public:
        type: boolean
      is_email_public:
        type: boolean
      is_first_name_public:
        type: boolean
      is_last_name_public:
        type: boolean
      is_phone_number_public:
        type: boolean
      is_profile_picture_public:
        type: boolean
      last_name:
        maxLength: 32
        minLength: 3
        type: string
      phone_number:
        type: string
      profile_picture_url:
        type: string
    type: object
  profile.UpdateProfileResponse:
    properties:
      academic_email:
        type: string
      academic_institution:
        type: string
      address:
        type: string
      authentication_credential_id:
        type: string
      bio:
        type: string
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: string
      is_academic_email_public:
        type: boolean
      is_academic_institution_public:
        type: boolean
      is_address_public:
        type: boolean
      is_bio_public:
        type: boolean
      is_email_public:
        type: boolean
      is_first_name_public:
        type: boolean
      is_last_name_public:
        type: boolean
      is_phone_number_public:
        type: boolean
      is_profile_picture_public:
        type: boolean
      last_name:
        type: string
      phone_number:
        type: string
      profile_picture_url:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: DECM (Decentralized Event Management) platform API for NFT ticketing,
    digital credentials, and academic identity verification.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: DECM Core
  version: "1.0"
paths:
  /api/v1/auth/request-google-oauth:
    get:
      consumes:
      - application/json
      description: Request Google OAuth
      operationId: request-google-oauth
      produces:
      - application/json
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.ErrResponse'
      summary: Request Google OAuth
      tags:
      - Auth
  /api/v1/auth/verify-google-oauth:
    get:
      consumes:
      - application/json
      description: Verify Google OAuth code
      operationId: verify-google-oauth
      parameters:
      - in: query
        name: code
        type: string
      - in: query
        name: state
        type: string
      - in: query
        name: code
        type: string
      - in: query
        name: state
        type: string
      produces:
      - application/json
      responses:
        "302":
          description: Found
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.ErrResponse'
      summary: Verify Google OAuth code
      tags:
      - Auth
  /api/v1/onboard/check-onboard-status:
    post:
      consumes:
      - application/json
      description: Check onboard status
      operationId: check-onboard-status
      parameters:
      - description: Method
        in: body
        name: method
        required: true
        schema:
          $ref: '#/definitions/onboard.CheckOnboardStatusRequest'
      - description: Access token
        in: body
        name: access_token
        schema:
          $ref: '#/definitions/onboard.CheckOnboardStatusRequest'
      - description: Expires in
        in: body
        name: expires_in
        schema:
          $ref: '#/definitions/onboard.CheckOnboardStatusRequest'
      - description: Sign message
        in: body
        name: sign_message
        schema:
          $ref: '#/definitions/onboard.CheckOnboardStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/onboard.CheckOnboardStatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/customerror.ErrResponse'
      summary: Check onboard status
      tags:
      - Onboard
  /api/v1/onboard/register-with-google-oauth:
    post:
      consumes:
      - application/json
      description: Register a new user with Google OAuth
      operationId: register-with-google-oauth
      parameters:
      - description: Access token
        in: body
        name: access_token
        required: true
        schema:
          $ref: '#/definitions/onboard.registerWithGoogleOAuthRequest'
      - description: Password
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/onboard.registerWithGoogleOAuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/onboard.registerWithGoogleOAuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.ErrResponse'
      summary: Register a new user with Google OAuth
      tags:
      - Onboard
  /api/v1/onboard/register-with-wallet:
    post:
      consumes:
      - application/json
      description: Register a new user with wallet address
      operationId: register-with-wallet
      parameters:
      - description: Signed message
        in: body
        name: signed_message
        required: true
        schema:
          $ref: '#/definitions/onboard.registerWithWalletRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.ErrResponse'
      summary: Register a new user with wallet address
      tags:
      - Onboard
  /api/v1/onboard/sign-message:
    get:
      description: Retrieve preset message for the client to sign to register
      operationId: get-register-sign-message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/onboard.getRegisterSignMessageResponse'
      summary: Get preset message for the client to sign to register
  /api/v1/profile:
    post:
      consumes:
      - application/json
      description: Create a profile
      operationId: create-profile
      parameters:
      - description: Profile
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/profile.CreateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/profile.CreateProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.Err'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/customerror.Err'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/customerror.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customerror.Err'
      summary: Create a profile
      tags:
      - Profile
  /api/v1/profile/credential/{credential_id}:
    patch:
      consumes:
      - application/json
      description: Update a profile by credential ID
      operationId: update-profile-by-credential-id
      parameters:
      - description: Credential ID
        in: path
        name: credential_id
        required: true
        type: string
      - description: Is Profile Picture Public
        in: body
        name: IsProfilePicturePublic
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Profile Picture URL
        in: body
        name: ProfilePictureUrl
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Is First Name Public
        in: body
        name: IsFirstNamePublic
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: First Name
        in: body
        name: FirstName
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Is Last Name Public
        in: body
        name: IsLastNamePublic
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Last Name
        in: body
        name: LastName
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Is Email Public
        in: body
        name: IsEmailPublic
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Email
        in: body
        name: Email
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Is Phone Number Public
        in: body
        name: IsPhoneNumberPublic
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Phone Number
        in: body
        name: PhoneNumber
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Is Address Public
        in: body
        name: IsAddressPublic
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Address
        in: body
        name: Address
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Is Academic Institution Public
        in: body
        name: IsAcademicInstitutionPublic
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Academic Institution
        in: body
        name: AcademicInstitution
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Is Academic Email Public
        in: body
        name: IsAcademicEmailPublic
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      - description: Academic Email
        in: body
        name: AcademicEmail
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/profile.UpdateProfileResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.Err'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/customerror.Err'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/customerror.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customerror.Err'
      summary: Update a profile by credential ID
      tags:
      - Profile
  /api/v1/profile/my:
    get:
      consumes:
      - application/json
      description: Get my profile
      operationId: get-my-profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Profile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/customerror.Err'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/customerror.Err'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/customerror.Err'
      summary: Get my profile
      tags:
      - Profile
swagger: "2.0"
