// Auto-generated TypeScript types for EventAccessManager contract
// This file is generated by scripts/generate-contract-types.js
// Do not edit this file directly

export const EventAccessManagerABI = [
    {
        type: "constructor",
        inputs: [
            {
                name: "decmAccessManagerAddr",
                type: "address",
                internalType: "address",
            },
            {
                name: "hostAddress",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "DECM_ACCESS_MANAGER",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "contract DecmAccessManager",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "DEFAULT_ADMIN_ROLE",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "checkIsAllowedMsgSender",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "checkIsHost",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "checkIsHostOrAdmin",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "checkIsIssuer",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "checkIsParticipant",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoleAdmin",
        inputs: [
            {
                name: "role",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "grantHostRole",
        inputs: [
            {
                name: "host",
                type: "address",
                internalType: "address",
            },
            {
                name: "signer",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "grantIssuerRole",
        inputs: [
            {
                name: "issuer",
                type: "address",
                internalType: "address",
            },
            {
                name: "signer",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "grantParticipantRole",
        inputs: [
            {
                name: "participant",
                type: "address",
                internalType: "address",
            },
            {
                name: "signer",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "grantParticipantRoleUsingAllowedMsgSender",
        inputs: [
            {
                name: "participant",
                type: "address",
                internalType: "address",
            },
            {
                name: "msgSender",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "grantRole",
        inputs: [
            {
                name: "role",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "hasRole",
        inputs: [
            {
                name: "role",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "recoverSigner",
        inputs: [
            {
                name: "signedMessageDigest",
                type: "string",
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "renounceRole",
        inputs: [
            {
                name: "role",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "callerConfirmation",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "requireAdmin",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
            {
                name: "msgSender",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "requireAllowedMsgSender",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "requireHostOrAdmin",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
            {
                name: "msgSender",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "requireHostOrAdminOrParticipant",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
            {
                name: "msgSender",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "requireParticipant",
        inputs: [
            {
                name: "addr",
                type: "address",
                internalType: "address",
            },
            {
                name: "msgSender",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "revokeIssuerRole",
        inputs: [
            {
                name: "issuer",
                type: "address",
                internalType: "address",
            },
            {
                name: "signer",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "revokeParticipantRole",
        inputs: [
            {
                name: "participant",
                type: "address",
                internalType: "address",
            },
            {
                name: "signer",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "revokeRole",
        inputs: [
            {
                name: "role",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "supportsInterface",
        inputs: [
            {
                name: "interfaceId",
                type: "bytes4",
                internalType: "bytes4",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "usedSignatures",
        inputs: [
            {
                name: "",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "HostRoleGranted",
        inputs: [
            {
                name: "host",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "granter",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "IssuerRoleGranted",
        inputs: [
            {
                name: "issuer",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "granter",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "IssuerRoleRevoked",
        inputs: [
            {
                name: "issuer",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "revoker",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "MsgSenderAllowed",
        inputs: [
            {
                name: "sender",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "granter",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "MsgSenderDisallowed",
        inputs: [
            {
                name: "sender",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "revoker",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ParticipantRoleGranted",
        inputs: [
            {
                name: "participant",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "granter",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ParticipantRoleRevoked",
        inputs: [
            {
                name: "participant",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "revoker",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleAdminChanged",
        inputs: [
            {
                name: "role",
                type: "bytes32",
                indexed: true,
                internalType: "bytes32",
            },
            {
                name: "previousAdminRole",
                type: "bytes32",
                indexed: true,
                internalType: "bytes32",
            },
            {
                name: "newAdminRole",
                type: "bytes32",
                indexed: true,
                internalType: "bytes32",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleGranted",
        inputs: [
            {
                name: "role",
                type: "bytes32",
                indexed: true,
                internalType: "bytes32",
            },
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "sender",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleRevoked",
        inputs: [
            {
                name: "role",
                type: "bytes32",
                indexed: true,
                internalType: "bytes32",
            },
            {
                name: "account",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "sender",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "AccessControlBadConfirmation",
        inputs: [],
    },
    {
        type: "error",
        name: "AccessControlUnauthorizedAccount",
        inputs: [
            {
                name: "account",
                type: "address",
                internalType: "address",
            },
            {
                name: "neededRole",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
    },
    {
        type: "error",
        name: "ECDSAInvalidSignature",
        inputs: [],
    },
    {
        type: "error",
        name: "ECDSAInvalidSignatureLength",
        inputs: [
            {
                name: "length",
                type: "uint256",
                internalType: "uint256",
            },
        ],
    },
    {
        type: "error",
        name: "ECDSAInvalidSignatureS",
        inputs: [
            {
                name: "s",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
    },
    {
        type: "error",
        name: "Themis__InvalidSignature",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__SignatureAlreadyUsed",
        inputs: [],
    },
] as const;

export type EventAccessManager = {
    abi: typeof EventAccessManagerABI;
};

export default EventAccessManagerABI;
