// Auto-generated TypeScript types for EventCertificate contract
// This file is generated by scripts/generate-contract-types.js
// Do not edit this file directly

export const EventCertificateABI = [
    {
        type: "constructor",
        inputs: [
            {
                name: "eventAccessManagerAddr",
                type: "address",
                internalType: "address",
            },
            {
                name: "eventAddr",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "EVENT",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "contract Event",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "EVENT_ACCESS_MANAGER",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "contract EventAccessManager",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "approve",
        inputs: [
            {
                name: "to",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "balanceOf",
        inputs: [
            {
                name: "owner",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "bulkMintParticipantCertificates",
        inputs: [
            {
                name: "params",
                type: "tuple[]",
                internalType: "struct EventCertificate.BulkMintParticipantCertificatesParams[]",
                components: [
                    {
                        name: "receiverAddress",
                        type: "address",
                        internalType: "address",
                    },
                    {
                        name: "userId",
                        type: "string",
                        internalType: "string",
                    },
                    {
                        name: "certificateId",
                        type: "string",
                        internalType: "string",
                    },
                    {
                        name: "issuerId",
                        type: "string",
                        internalType: "string",
                    },
                    {
                        name: "encryptedUserData",
                        type: "string",
                        internalType: "string",
                    },
                    {
                        name: "backendEncryptedUserData",
                        type: "string",
                        internalType: "string",
                    },
                    {
                        name: "issuerAddresses",
                        type: "address[]",
                        internalType: "address[]",
                    },
                ],
            },
            {
                name: "signMessage",
                type: "string",
                internalType: "string",
            },
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getApproved",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getTokenData",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "hashEthereumMessage",
        inputs: [
            {
                name: "rawMessage",
                type: "string",
                internalType: "string",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
        stateMutability: "pure",
    },
    {
        type: "function",
        name: "isApprovedForAll",
        inputs: [
            {
                name: "owner",
                type: "address",
                internalType: "address",
            },
            {
                name: "operator",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "mintNft",
        inputs: [
            {
                name: "receiverAddress",
                type: "address",
                internalType: "address",
            },
            {
                name: "userId",
                type: "string",
                internalType: "string",
            },
            {
                name: "certificateId",
                type: "string",
                internalType: "string",
            },
            {
                name: "issuerId",
                type: "string",
                internalType: "string",
            },
            {
                name: "encryptedUserData",
                type: "string",
                internalType: "string",
            },
            {
                name: "backendEncryptedUserData",
                type: "string",
                internalType: "string",
            },
            {
                name: "issuerAddresses",
                type: "address[]",
                internalType: "address[]",
            },
            {
                name: "signMessage",
                type: "string",
                internalType: "string",
            },
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "name",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "ownerOf",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "participantSignedCertificate",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "recoverSigner",
        inputs: [
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "message",
                type: "string",
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
            {
                name: "contractAddress",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "recoverSigner",
        inputs: [
            {
                name: "messageHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "pure",
    },
    {
        type: "function",
        name: "revokeCertificate",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "signMessage",
                type: "string",
                internalType: "string",
            },
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "safeTransferFrom",
        inputs: [
            {
                name: "from",
                type: "address",
                internalType: "address",
            },
            {
                name: "to",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "safeTransferFrom",
        inputs: [
            {
                name: "from",
                type: "address",
                internalType: "address",
            },
            {
                name: "to",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "data",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "setApprovalForAll",
        inputs: [
            {
                name: "operator",
                type: "address",
                internalType: "address",
            },
            {
                name: "approved",
                type: "bool",
                internalType: "bool",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "supportsInterface",
        inputs: [
            {
                name: "interfaceId",
                type: "bytes4",
                internalType: "bytes4",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "symbol",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "tokenURI",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "transferFrom",
        inputs: [
            {
                name: "from",
                type: "address",
                internalType: "address",
            },
            {
                name: "to",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "Approval",
        inputs: [
            {
                name: "owner",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "approved",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "tokenId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ApprovalForAll",
        inputs: [
            {
                name: "owner",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "operator",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "approved",
                type: "bool",
                indexed: false,
                internalType: "bool",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "CertificateMinted",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "receiverAddress",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "certificateId",
                type: "string",
                indexed: false,
                internalType: "string",
            },
            {
                name: "userId",
                type: "string",
                indexed: false,
                internalType: "string",
            },
            {
                name: "issuerId",
                type: "string",
                indexed: false,
                internalType: "string",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "CertificateRevoked",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ParticipantSignedCertificate",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
            {
                name: "receiverAddress",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Transfer",
        inputs: [
            {
                name: "from",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "to",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "tokenId",
                type: "uint256",
                indexed: true,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "ECDSAInvalidSignature",
        inputs: [],
    },
    {
        type: "error",
        name: "ECDSAInvalidSignatureLength",
        inputs: [
            {
                name: "length",
                type: "uint256",
                internalType: "uint256",
            },
        ],
    },
    {
        type: "error",
        name: "ECDSAInvalidSignatureS",
        inputs: [
            {
                name: "s",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
    },
    {
        type: "error",
        name: "ERC721IncorrectOwner",
        inputs: [
            {
                name: "sender",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "owner",
                type: "address",
                internalType: "address",
            },
        ],
    },
    {
        type: "error",
        name: "ERC721InsufficientApproval",
        inputs: [
            {
                name: "operator",
                type: "address",
                internalType: "address",
            },
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
    },
    {
        type: "error",
        name: "ERC721InvalidApprover",
        inputs: [
            {
                name: "approver",
                type: "address",
                internalType: "address",
            },
        ],
    },
    {
        type: "error",
        name: "ERC721InvalidOperator",
        inputs: [
            {
                name: "operator",
                type: "address",
                internalType: "address",
            },
        ],
    },
    {
        type: "error",
        name: "ERC721InvalidOwner",
        inputs: [
            {
                name: "owner",
                type: "address",
                internalType: "address",
            },
        ],
    },
    {
        type: "error",
        name: "ERC721InvalidReceiver",
        inputs: [
            {
                name: "receiver",
                type: "address",
                internalType: "address",
            },
        ],
    },
    {
        type: "error",
        name: "ERC721InvalidSender",
        inputs: [
            {
                name: "sender",
                type: "address",
                internalType: "address",
            },
        ],
    },
    {
        type: "error",
        name: "ERC721NonexistentToken",
        inputs: [
            {
                name: "tokenId",
                type: "uint256",
                internalType: "uint256",
            },
        ],
    },
    {
        type: "error",
        name: "EventCertificate__CertificateNotValid",
        inputs: [],
    },
    {
        type: "error",
        name: "EventCertificate__NotHost",
        inputs: [],
    },
    {
        type: "error",
        name: "EventCertificate__NotHostOrAdmin",
        inputs: [],
    },
    {
        type: "error",
        name: "EventCertificate__NotParticipant",
        inputs: [],
    },
    {
        type: "error",
        name: "EventCertificate__TokenIdOutOfBounds",
        inputs: [],
    },
    {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
        inputs: [],
    },
    {
        type: "error",
        name: "StringsInvalidAddressFormat",
        inputs: [],
    },
    {
        type: "error",
        name: "StringsInvalidChar",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidCaller",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidContract",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidDigestHash",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidSignature",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidSigner",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__SignatureExpired",
        inputs: [],
    },
] as const;

export type EventCertificate = {
    abi: typeof EventCertificateABI;
};

export default EventCertificateABI;
