// Auto-generated TypeScript types for Event contract
// This file is generated by scripts/generate-contract-types.js
// Do not edit this file directly

export const EventABI = [
    {
        type: "constructor",
        inputs: [
            {
                name: "eventAccessManagerAddr",
                type: "address",
                internalType: "address",
            },
            {
                name: "_eventName",
                type: "string",
                internalType: "string",
            },
            {
                name: "_eventDescription",
                type: "string",
                internalType: "string",
            },
            {
                name: "_seatsCount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "EVENT_ACCESS_MANAGER",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "contract EventAccessManager",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "addParticipant",
        inputs: [
            {
                name: "participantAddress",
                type: "address",
                internalType: "address",
            },
            {
                name: "signedMessageDigest",
                type: "string",
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "confirmEvent",
        inputs: [
            {
                name: "signedMessageDigest",
                type: "string",
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "currentSeatsCount",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "eventDescription",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "eventName",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "eventStatus",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint8",
                internalType: "enum Event.EventStatus",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getEventDescription",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getEventName",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getParticipants",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address[]",
                internalType: "address[]",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "leaveEvent",
        inputs: [
            {
                name: "signedMessageDigest",
                type: "string",
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "recoverSigner",
        inputs: [
            {
                name: "signedMessageDigest",
                type: "string",
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "removeParticipant",
        inputs: [
            {
                name: "participantAddress",
                type: "address",
                internalType: "address",
            },
            {
                name: "signedMessageDigest",
                type: "string",
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "seatsCount",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "updateEvent",
        inputs: [
            {
                name: "_eventName",
                type: "string",
                internalType: "string",
            },
            {
                name: "_eventDescription",
                type: "string",
                internalType: "string",
            },
            {
                name: "_seatsCount",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_eventStatus",
                type: "uint8",
                internalType: "enum Event.EventStatus",
            },
            {
                name: "signedMessageDigest",
                type: "string",
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "usedSignatures",
        inputs: [
            {
                name: "",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bool",
                internalType: "bool",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "event",
        name: "AddedParticipant",
        inputs: [
            {
                name: "participant",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "EventConfirmed",
        inputs: [],
        anonymous: false,
    },
    {
        type: "event",
        name: "EventUpdated",
        inputs: [
            {
                name: "eventName",
                type: "string",
                indexed: false,
                internalType: "string",
            },
            {
                name: "eventDescription",
                type: "string",
                indexed: false,
                internalType: "string",
            },
            {
                name: "seatsCount",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "eventStatus",
                type: "uint8",
                indexed: false,
                internalType: "enum Event.EventStatus",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ParticipantSigned",
        inputs: [
            {
                name: "participant",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "signature",
                type: "bytes32",
                indexed: false,
                internalType: "bytes32",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RemovedParticipant",
        inputs: [
            {
                name: "participant",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "SignatureUsed",
        inputs: [
            {
                name: "transactor",
                type: "address",
                indexed: false,
                internalType: "address",
            },
            {
                name: "signer",
                type: "address",
                indexed: false,
                internalType: "address",
            },
            {
                name: "contractAddress",
                type: "address",
                indexed: false,
                internalType: "address",
            },
            {
                name: "functionName",
                type: "string",
                indexed: false,
                internalType: "string",
            },
            {
                name: "signedMessageDigest",
                type: "string",
                indexed: false,
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                indexed: false,
                internalType: "bytes",
            },
            {
                name: "timestamp",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "ECDSAInvalidSignature",
        inputs: [],
    },
    {
        type: "error",
        name: "ECDSAInvalidSignatureLength",
        inputs: [
            {
                name: "length",
                type: "uint256",
                internalType: "uint256",
            },
        ],
    },
    {
        type: "error",
        name: "ECDSAInvalidSignatureS",
        inputs: [
            {
                name: "s",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
    },
    {
        type: "error",
        name: "Themis__InvalidSignature",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__SignatureAlreadyUsed",
        inputs: [],
    },
] as const;

export type Event = {
    abi: typeof EventABI;
};

export default EventABI;
