// Auto-generated TypeScript types for Event contract
// This file is generated by scripts/generate-contract-types.js
// Do not edit this file directly

export const EventABI = [
    {
        type: "constructor",
        inputs: [
            {
                name: "eventAccessManagerAddr",
                type: "address",
                internalType: "address",
            },
            {
                name: "_eventName",
                type: "string",
                internalType: "string",
            },
            {
                name: "_eventDescription",
                type: "string",
                internalType: "string",
            },
            {
                name: "_seatsCount",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "EVENT_ACCESS_MANAGER",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "contract EventAccessManager",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "addParticipant",
        inputs: [
            {
                name: "participantAddress",
                type: "address",
                internalType: "address",
            },
            {
                name: "signMessage",
                type: "string",
                internalType: "string",
            },
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "confirmEvent",
        inputs: [
            {
                name: "signMessage",
                type: "string",
                internalType: "string",
            },
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "currentSeatsCount",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "eventDescription",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "eventName",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "eventStatus",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint8",
                internalType: "enum Event.EventStatus",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getEventDescription",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getEventName",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "string",
                internalType: "string",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getParticipants",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "address[]",
                internalType: "address[]",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "hashEthereumMessage",
        inputs: [
            {
                name: "rawMessage",
                type: "string",
                internalType: "string",
            },
        ],
        outputs: [
            {
                name: "",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
        stateMutability: "pure",
    },
    {
        type: "function",
        name: "leaveEvent",
        inputs: [
            {
                name: "signMessage",
                type: "string",
                internalType: "string",
            },
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "recoverSigner",
        inputs: [
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "message",
                type: "string",
                internalType: "string",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
            {
                name: "contractAddress",
                type: "address",
                internalType: "address",
            },
        ],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "recoverSigner",
        inputs: [
            {
                name: "messageHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [
            {
                name: "",
                type: "address",
                internalType: "address",
            },
        ],
        stateMutability: "pure",
    },
    {
        type: "function",
        name: "removeParticipant",
        inputs: [
            {
                name: "participantAddress",
                type: "address",
                internalType: "address",
            },
            {
                name: "signMessage",
                type: "string",
                internalType: "string",
            },
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "seatsCount",
        inputs: [],
        outputs: [
            {
                name: "",
                type: "uint256",
                internalType: "uint256",
            },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "updateEvent",
        inputs: [
            {
                name: "_eventName",
                type: "string",
                internalType: "string",
            },
            {
                name: "_eventDescription",
                type: "string",
                internalType: "string",
            },
            {
                name: "_seatsCount",
                type: "uint256",
                internalType: "uint256",
            },
            {
                name: "_eventStatus",
                type: "uint8",
                internalType: "enum Event.EventStatus",
            },
            {
                name: "signMessage",
                type: "string",
                internalType: "string",
            },
            {
                name: "digestHash",
                type: "bytes32",
                internalType: "bytes32",
            },
            {
                name: "signature",
                type: "bytes",
                internalType: "bytes",
            },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "AddedParticipant",
        inputs: [
            {
                name: "participant",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "EventConfirmed",
        inputs: [],
        anonymous: false,
    },
    {
        type: "event",
        name: "EventUpdated",
        inputs: [
            {
                name: "eventName",
                type: "string",
                indexed: false,
                internalType: "string",
            },
            {
                name: "eventDescription",
                type: "string",
                indexed: false,
                internalType: "string",
            },
            {
                name: "seatsCount",
                type: "uint256",
                indexed: false,
                internalType: "uint256",
            },
            {
                name: "eventStatus",
                type: "uint8",
                indexed: false,
                internalType: "enum Event.EventStatus",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ParticipantSigned",
        inputs: [
            {
                name: "participant",
                type: "address",
                indexed: true,
                internalType: "address",
            },
            {
                name: "signature",
                type: "bytes32",
                indexed: false,
                internalType: "bytes32",
            },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RemovedParticipant",
        inputs: [
            {
                name: "participant",
                type: "address",
                indexed: true,
                internalType: "address",
            },
        ],
        anonymous: false,
    },
    {
        type: "error",
        name: "ECDSAInvalidSignature",
        inputs: [],
    },
    {
        type: "error",
        name: "ECDSAInvalidSignatureLength",
        inputs: [
            {
                name: "length",
                type: "uint256",
                internalType: "uint256",
            },
        ],
    },
    {
        type: "error",
        name: "ECDSAInvalidSignatureS",
        inputs: [
            {
                name: "s",
                type: "bytes32",
                internalType: "bytes32",
            },
        ],
    },
    {
        type: "error",
        name: "Event__AccessManagerCannotBeZeroAddress",
        inputs: [],
    },
    {
        type: "error",
        name: "Event__AddressCannotBeZero",
        inputs: [],
    },
    {
        type: "error",
        name: "Event__CannotReduceSeatsCount",
        inputs: [],
    },
    {
        type: "error",
        name: "Event__CantConfirmEvent",
        inputs: [
            {
                name: "message",
                type: "string",
                internalType: "string",
            },
        ],
    },
    {
        type: "error",
        name: "Event__InvalidEventName",
        inputs: [],
    },
    {
        type: "error",
        name: "Event__InvalidSignature",
        inputs: [],
    },
    {
        type: "error",
        name: "Event__ParticipantIsAlreadyJoined",
        inputs: [],
    },
    {
        type: "error",
        name: "Event__ParticipantIsNotJoined",
        inputs: [],
    },
    {
        type: "error",
        name: "Event__SeatsCountReached",
        inputs: [],
    },
    {
        type: "error",
        name: "StringsInvalidAddressFormat",
        inputs: [],
    },
    {
        type: "error",
        name: "StringsInvalidChar",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidCaller",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidContract",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidDigestHash",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidSignature",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__InvalidSigner",
        inputs: [],
    },
    {
        type: "error",
        name: "Themis__SignatureExpired",
        inputs: [],
    },
] as const;

export type Event = {
    abi: typeof EventABI;
};

export default EventABI;
