// Auto-generated index file for contract types
// This file is generated by scripts/generate-contract-types.js
// Do not edit this file directly

import { EventABI } from './Event';
import { EventAccessManagerABI } from './EventAccessManager';
import { EventTicketABI } from './EventTicket';
import { EventCertificateABI } from './EventCertificate';
import { DecmAccessManagerABI } from './DecmAccessManager';

export { EventABI } from './Event';
export { EventAccessManagerABI } from './EventAccessManager';
export { EventTicketABI } from './EventTicket';
export { EventCertificateABI } from './EventCertificate';
export { DecmAccessManagerABI } from './DecmAccessManager';

// Re-export all ABIs for convenience
export const ABIs = {
  EventContract: EventABI,
  EventAccessManagerContract: EventAccessManagerABI,
  EventTicketContract: EventTicketABI,
  EventCertificateContract: EventCertificateABI,
  DecmAccessManagerContract: DecmAccessManagerABI,
} as const;
